---
ID: "3dd2119d-8cb6-45db-88bb-3d04c0f50a75"
Parent: "1a614423-81ce-430e-b368-3341275e754d"
Template: "1a614423-81ce-430e-b368-3341275e754d"
Path: /sitecore/templates/Feature/SC_Playground/Components/ProfileDetail/Profile/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240627T133723Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "53009008-9f0c-46cc-ad0b-6de00299f6c4"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240627T133723Z
