---
ID: "59b2aae7-aa53-4dc2-a82a-547a0cc77c6c"
Parent: "9e11cd5f-421c-48fa-a64e-6c455c54ac66"
Template: "9e11cd5f-421c-48fa-a64e-6c455c54ac66"
Path: /sitecore/templates/Project/SCPlayground/components/PromoCards/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240625T071609Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "6104f9e4-6a60-45b9-8d0f-4f8be23075db"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240625T071609Z
