---
ID: "c47843ba-d100-45fc-8c86-32c7cd84f9ae"
Parent: "2ee92d8d-aa06-4aca-9300-5c8bbe569d0b"
Template: "2ee92d8d-aa06-4aca-9300-5c8bbe569d0b"
Path: /sitecore/templates/Feature/SC_Playground/Components/Promo Component/Promo Folder/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{E2328AD1-0B9E-4C03-8AFB-9FE52C6CA39E}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240627T045455Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "69f01279-4e45-434f-bf27-8dd815fc781e"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240627T045537Z
