---
ID: "4b2b547e-f2ff-453c-9917-e2ba9846cf3e"
Parent: "6926a76c-c3ac-4490-9821-8cc473e2ae64"
Template: "db2d8a4d-c889-4f00-8eca-ad1ed22b337b"
Path: /sitecore/content/Horizontal Training/SC_Playground/Settings
Languages:
- Language: en
  Versions:
  - Version: 1
